### ISSUE TITLE
Regex filters support

### ISSUE THREAD

**Issue by dimzon** [cathugger/mkp224o#5] opened 2018-01-20 03:24 UTC
please add

**Comment by cathugger** [comment] 2018-01-20 14:39
I'm still unsure whether it's worth adding this or not.
It'd need to use some external lib to do actual regex stuff.
Also some things currently are optimized without regex in mind:
- we actually do not convert public key to text form before we check against it, we convert text filters to binary masks and use them. that's faster. I'm not sure how fast my base32_to code is.
- we do not calculate SHA3 checksum before we check either. it's only done when we find public key we want. I'm not sure if we should even do that, as it will result in slowdown. but without it we wouldn't be able to check last few characters with regex.

There is also question which regex library to use. There are quite a few choices (https://rust-leipzig.github.io/regex/2017/03/28/comparison-of-regex-engines/). pcre would probably be easiest to install for most people but it's suboptimal performance-wise. I haven't decided on any yet.

**Comment by cathugger** [comment] 2018-01-20 14:56
OK I think initially I should do PCRE (possibly with JIT) support as it has C API and is easy to install on most systems.

**Comment by cathugger** [comment] 2018-01-20 20:00
@dimzon added https://github.com/cathugger/mkp224o/commit/e32e8e06f6e7018354dd56180d064e6fbc9f3181
it cannot match few characters of onion at the end because they are checksum bytes and are currently not calculated before we do checking.
plz rebuild configure script with `./autogen`, rerun `./configure` with --enable-regex, make clean, recompile and see if it works for you

**Comment by dimzon** [comment] 2018-01-21 15:34
```
main.c.o: In function `filters_add':
main.c:(.text+0x56): undefined reference to `pcre2_compile_8'
main.c:(.text+0x6f): undefined reference to `pcre2_jit_compile_8'
main.c:(.text+0x117): undefined reference to `pcre2_get_error_message_8'
main.c.o: In function `dofastwork':
main.c:(.text+0x3a0): undefined reference to `pcre2_match_data_create_8'
main.c:(.text+0x56e): undefined reference to `pcre2_match_8'
main.c:(.text+0x62e): undefined reference to `pcre2_match_8'
main.c:(.text+0x7cf): undefined reference to `pcre2_match_data_free_8'
main.c.o: In function `dowork':
main.c:(.text+0x840): undefined reference to `pcre2_match_data_create_8'
main.c:(.text+0x9f6): undefined reference to `pcre2_match_8'
main.c:(.text+0xab6): undefined reference to `pcre2_match_8'
main.c:(.text+0xc07): undefined reference to `pcre2_match_data_free_8'
main.c.o: In function `main':
main.c:(.text.startup+0x688): undefined reference to `pcre2_code_free_8'
collect2: error: ld returned 1 exit status
Makefile:67: recipe for target 'mkp224o' failed
make: *** [mkp224o] Error 1

```

**Comment by cathugger** [comment] 2018-01-21 18:33
@dimzon what distro are you using?
also what doesn `pcre-config --cflags` and `pcre-config --libs8` print?
also can you paste few lines before error ones?

**Comment by cathugger** [comment] 2018-01-21 21:20
I just remembered that once on ubuntu I had quite odd gcc behavior that it'd refuse to link in libraries if they were specified before object files. putting libraries at the end helped. I'll try this.

**Comment by cathugger** [comment] 2018-01-21 21:24
@dimzon https://github.com/cathugger/mkp224o/commit/b1549bdb1a453c855e1b26c40b358c133a1ebf3f
plz rebuild with same instructions as in https://github.com/cathugger/mkp224o/issues/5#issuecomment-359198070
tell me if this worked

**Comment by dimzon** [comment] 2018-01-22 21:50
it works now
btw very strange regexp behavior - I think i need to post bugreports to pcre:
^(bla1|bla2|bla3|...|blaN)*((.)\1{5,222})

explanation: some of pre-defined prefixes (bla1-blaN) followed by at least 5 same characters for example: bla2fffff or  bla3uuuuuuuu

this regex stop working after some amount of blaN (got pcre compilation error). removing 1-2 blaN makes it work again...

**Comment by cathugger** [comment] 2018-01-23 15:40
well. if you can reproduce these with pcre2grep/pcre2test then it's not my thing. probably not worth investigating for me as I don't see regexes like that to be too useful.
actually I was thinking of making ^ implicit, so that it will be more consistent with how non-regex filters behave.
I mean, that expressions `^aaa` and `aaa` would behave the same. So there will be small behavior change, sorry if it broke any of workflow.

**Comment by cathugger** [comment] 2018-01-26 18:55
seems this is working well so far.
I guess I can close this ticket.
reopen if there is any stuff to discuss.

**Closed by cathugger** 2018-01-26 18:55 UTC
Labels: enhancement

**Comment by cathugger** [comment] 2018-07-03 19:13
matching of end of onion address is not supported because of performance optimization.
at the end of address, checksum is stored, and it's SHA3 so computing it before checking would slow down cases where checking of end of address isn't needed.
regex filter you mentioned doesn't end with `$` therefore only smallest portion (2 first characters) are matched.
they all end with d because of constant version byte which is included in all v3 addresses ([specification](https://gitweb.torproject.org/torspec.git/plain/rend-spec-v3.txt), [ONIONADDRESS] section).

**Comment by VityaSchel** [comment] 2021-07-04 23:01
> matching of end of onion address is not supported because of performance optimization.
> at the end of address, checksum is stored, and it's SHA3 so computing it before checking would slow down cases where checking of end of address isn't needed.
> regex filter you mentioned doesn't end with `$` therefore only smallest portion (2 first characters) are matched.
> they all end with d because of constant version byte which is included in all v3 addresses ([specification](https://gitweb.torproject.org/torspec.git/plain/rend-spec-v3.txt), [ONIONADDRESS] section).

Hello! Huge thanks to you for replying to comments on issues. I hope you will reply to this too. Can you please tell me why this regex doesn't work when I run it?

```
^.
```

These are not working as well:

`^[^1]`, `\D`, `^[ab-d]`

They are the actual regex patterns combined using pcre specification, but it gives me 0 results every time:

```
>calc/sec:4941060.199405, succ/sec:0.000000, rest/sec:38.757061, elapsed:0.103207sec
>calc/sec:4737791.755692, succ/sec:0.000000, rest/sec:0.000000, elapsed:1.138491sec
>calc/sec:4561531.020470, succ/sec:0.000000, rest/sec:0.000000, elapsed:2.167086sec
```

What is the problem? Btw I'm actually trying to generate an address without digits using this regex: ^\D{56} maybe there is another way to do that? I reconfigured it with --enable-regex and then I ran gmake, still gives 0 results.

my system: mac os big sur, intel
prce2 installed

**Comment by queesamor** [comment] 2021-12-26 00:53
FYI: I had to modify line 6 of /contrib/docker/Dockerfile at https://github.com/cathugger/mkp224o/commit/1e18c10a117b335f77dd845ac8e7284def291c48 to this:
`RUN apk add --no-cache gcc libsodium-dev make autoconf build-base pcre2-dev`
in order for the Docker build to succeed with this on line 13:
`&& ./configure --enable-regex \`


I had to search through the issues to even discover that you'd included regex support (thank you for this, by the way).
Might it be valuable to add guidance to the repository's main readme, including 1) regex is possible w/ this configure flag; 2) pcre2-dev is a required package for this to succeed; and possibly 3) make sure to add pcre2-dev to the Dockerfile if you plan to use --enable-regex ?

**Comment by VityaSchel** [comment] 2022-06-29 17:02
и как
