### ISSUE TITLE
Segmentation fault when using regex filters

### ISSUE THREAD

**Issue by FliegendeWurst** [cathugger/mkp224o#9] opened 2018-06-08 09:34 UTC

**Comment by cathugger** [comment] 2018-06-16 12:41
seems to be caused by last commit's `pthread_attr_setstacksize(tattrp,20<<10);`. increasing to 80KiB (iirc, musl default) seems to fix at least for simple cases.
sorry for delay, haven't noticed this issue.

**Comment by cathugger** [comment] 2018-06-16 12:48
fixed in cf4443b7fdbaf8f528e3c4340d4faf2318a19f9d

**Closed by cathugger** 2018-06-16 12:48 UTC
