### ISSUE TITLE
YAML secret key use with ADD_ONION

### ISSUE THREAD

**Issue by nextwhopper** [cathugger/mkp224o#24] opened 2019-05-30 14:23 UTC
Thanks for your sharing your work and sorry for my newbie question.

I'm trying to use the secret key generated by mkp224o and saved with -y as YAML, with the `ADD_ONION ED22519-V3:...` command through Tor controller, but I am getting `Error: Failed to decode ED25519-V3 key`.

Doing `ADD_ONION NEW:ED22519-V3 ...` returns a private key with 86 length while on YAML I find secret keys of 128 length.

I tried using the first and last 86/64 characters but I'm getting a different service IDs than expected.
Anyone can give me any leads?
Thanks

**Comment by cathugger** [comment] 2019-05-30 23:11
If I recall correctly, ED22519-V3 requires base64 of just secret key (64 bytes raw data).
current pseudo-yaml output puts out header used in tor' secret keys stored on disk too (which is a bit silly now when I think of it, but it was initially coded by someone else that way and I wasn't aware of what ADD_ONION uses so it's left that way now and changing it could be bad for compatibility).
you're second person who brought that up so I might need to do something about it, and this ticket is probably right place for that.
for now, though, you need to skip first 32 bytes of raw secret key file (not base64'd thing but hs_ed25519_secret_key output with -Y flag, or manually unbase64'd), and then base64 encode that.
the way you tried cutting base64'd string didn't work because relevant bits aren't aligned to base64 characters (each char of base64 is 6 bits, 32 bytes = 256, 256 / 6 = 42.66666666667).
ED25519-V3: takes in only secret key, and first 32 bytes of hs_ed25519_secret_key are zero-padded header, and thing output in YAML mode also includes that header.
above might be bit unclear because I'm a bit sleepy, feel free to ask more if you don't get that.

**Comment by nextwhopper** [comment] 2019-05-31 03:59
Awesome, it worked, thank you!

Feel free to close this issue if you want.

**Comment by mrmabi** [comment] 2019-09-22 11:56
Definetly You're Computer Scientist.anyway, Best of luck for your Hardwork! :)
You have any spare time?

**Comment by cathugger** [comment] 2019-09-23 22:03
it's easy to change but if anyone use different versions for -y/-Y piping, it'll break.
that was my main concern. I really have no idea if anyone uses it this way. maybe it's just all in my head.
I guess I should just do that for new version, and add to release notes or somewhere like that that it may break -y/-Y stuff with older -Y receivers.

**Comment by cathugger** [comment] 2020-01-17 19:29
FYI I added `--rawyaml` flag to master now. will be part of next release.
it should output compatible with what tor controller protocol expects.
default will remain with with boilerplate and I don't plan removing that (so no compatibility break).
if `-y` is used with `--rawyaml`, `-Y` has to be used with `--rawyaml` too otherwise it won't parse it right.

**Comment by sharifzadesina** [comment] 2020-04-29 16:21
Thank you for the fix. Is this feature released yet?

**Comment by cathugger** [comment] 2020-05-06 14:01
Not yet, it will be in v1.5.0 which will be released when I feel like allocating few hours to package source / make scripts to build with mingw / sign everything / upload it.

**Comment by cathugger** [comment] 2020-05-06 14:01
It shouldn't be really difficult to just clone master and use that though.

**Comment by cathugger** [comment] 2020-05-23 19:23
v0.5.0 released.

**Closed by cathugger** 2020-05-23 19:23 UTC
Labels: enhancement

**Comment by mriamnot** [comment] 2022-12-11 11:52
sorry for newbie question i don;t know code and can do basic command on cmd.

i am using windows and generated a onion address using the command ^cute -y -n 1

the problem is i am going to use the key in tor browser. and it needed three files, which i am finding hard to create manually.

can anyone guide me how to create three files which i need. hostname, public key, secret key. or what command i need to run so the generated key be exported to a folder and i can use it with tor browser.

i tried to copy/paste the keys from the cmd and created a file using notepad, which the key showing is invalid.
